I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 210, in script
    t "このかっこいいチックトックリールを見よう"
Exception: Sayer 't' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 210, in script
    t "このかっこいいチックトックリールを見よう"
  File "C:\Users\alice\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\alice\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\alice\Downloads\renpy-8.3.2-sdk\renpy-8.3.2-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 't' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
JAPN 300 Final Project 1.0
Thu Nov 14 13:35:21 2024
