I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 84, in script
    シメキリ　"明日は期末試験の日だ！準備をしなければいけないんだ。そして、今日勉強しよう。え？"
Exception: Sayer 'シメキリ' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 84, in script
    シメキリ　"明日は期末試験の日だ！準備をしなければいけないんだ。そして、今日勉強しよう。え？"
  File "/Users/camilo/Documents/Brown/Sophomore/japn300/renpy-8.3.2-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Users/camilo/Documents/Brown/Sophomore/japn300/renpy-8.3.2-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/camilo/Documents/Brown/Sophomore/japn300/renpy-8.3.2-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'シメキリ' is not defined.

macOS-14.6.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
JAPN 300 Final Project 1.0
Wed Nov 13 17:03:42 2024
